name: Build PMX11

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install SDL2
      run: sudo apt-get install -y libsdl2-dev

    - name: Install dependencies
      run: |
        python -m venv .venv
        . .venv/bin/activate
        pip install -r requirements.txt

    - name: Build PMX11
      run: make build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pmx11-build
        path: build/pmx11
        retention-days: 7

